# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 049dcbb65be6b3336fcd63bad11881dae3ae83eac1c75c72fd3a08fb4116f6f82be7b9abcdbd0a64280b9f88b070b256a00a233fba6e175f11a0abceb1324869

test:
  secret_key_base: d797d8e8bf96133f094eb94d4e24ff5c2876a77977348288f2806bd91301f170c161e59e89cef647cc2e9b346ae336f8717e17e75756e8eaf18c3892de2439bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
